#
# Docker compose file for TANGO database and database device server
#
# Defines:
#   - tangodb: MariaDB database with TANGO schema
#   - databaseds: TANGO database device server
#   - rsyslog-csplmc: rsyslog service for logger
#   - cspmaster: CspMaster device
#
# Requires:
#   - None
#
version: '2.2'

services:
  csp_dsconfig:
    image: nexus.engageska-portugal.pt/ska-docker/tango-dsconfig:latest
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}csp_dsconfig
    depends_on:
      - databaseds
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=60 --strict --
             json2tango -w -a -u csplmc/csplmc/data/csplmc_dsconfig.json sleep infinity"
    volumes:
      - .:/csplmc

  cspsubarray01:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/csplmc:latest
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}cspsubarray01
    depends_on:
      - csp_dsconfig
      - cspmaster
      - rsyslog-csplmc
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             /venv/bin/python /app/csplmc/CspSubarray/CspSubarray/CspSubarray.py sub1"
    volumes_from:
      - rsyslog-csplmc:rw

  cspmaster:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/csplmc:latest
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}cspmaster
    depends_on:
      - csp_dsconfig
      - cbfmaster
      - rsyslog-csplmc
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             /venv/bin/python /app/csplmc/CspMaster/CspMaster/CspMaster.py csp"
    volumes_from:
      - rsyslog-csplmc:rw

  rsyslog-csplmc: 
    image: jumanjiman/rsyslog
    container_name: ${CONTAINER_NAME_PREFIX}rsyslog-csplmc
    network_mode: ${NETWORK_MODE}
